- build: examples/1_WakeOnMove
  photon: [0.7.0, 1.0.0, 1.2.1, 1.4.4]
  p1: [latest]
  electron: [0.7.0, 1.0.0]
  argon: [latest]
  boron: [0.9.0, 1.5.1-rc.1, latest]
- build: examples/2_Samples
  photon: [latest]
- build: examples/3_I2C
  electron: [latest]
- build: examples/4_Position
  photon: [latest]
- build: examples/5_Movement
  photon: [latest]
- build: examples/6_SPI1
  photon: [1.5.0, 1.5.1-rc.1]
